name: Build Flutter APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Switch to Flutter project directory
        run: cd advena_flutter

      - name: Flutter pub get
        working-directory: advena_flutter
        run: flutter pub get

      - name: Prepare Firebase Options
        working-directory: advena_flutter
        run: echo "$FIREBASE_OPTIONS" > lib/firebase_options.dart

      - name: List
        working-directory: advena_flutter
        run: cd lib && ls

      - name: Build APK
        working-directory: advena_flutter
        run: flutter build apk --release
