name: Flutter Build DEV

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
  
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install dependencies
        run: flutter pub get
        working-directory: advena_flutter

      - name: Generate firebase_options.dart
        run: |
          echo "$FIREBASE_OPTIONS_CONTENT" > advena_flutter/lib/firebase_options.dart
        env:
          FIREBASE_OPTIONS_CONTENT: ${{ secrets.FIREBASE_OPTIONS }}

      - name: Run Flutter build
        run: flutter build apk --no-pub
        working-directory: advena_flutter
