name: Flutter Deploy Release

on:
  push:
    branches:
      - idx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install dependencies
        run: flutter pub get
        working-directory: advena_flutter

      - name: Create .env file
        run: echo "TICKETMASTER_API_KEY=${{ secrets.TICKETMASTER_API_KEY }}" > advena_flutter/.env

      - name: Generate firebase_options.dart
        run: echo "$FIREBASE_OPTIONS_CONTENT" > advena_flutter/lib/firebase_options.dart
        env:
          FIREBASE_OPTIONS_CONTENT: ${{ secrets.FIREBASE_OPTIONS }}

      - name: Run Flutter build APK release
        run: flutter build apk --release
        working-directory: advena_flutter

      - name: Move APK to root of workspace
        run: mv advena_flutter/build/app/outputs/flutter-apk/release/app-release.apk $GITHUB_WORKSPACE/app-release.apk

      - name: LS Workspace
        run: ls
        working-directory: $GITHUB_WORKSPACE

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          app-name: 'ameyplayservice'
          package: '$GITHUB_WORKSPACE/app-release.apk'
