name: Release

on:
  workflow_run:
    workflows: ['Flutter Build Master']
    types: [completed]
      
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract commit message
        id: get_message
        run: | 
          commit_body="$(git log -1 --pretty=%B)"
          echo "Commit message body: $commit_body"

          tag_name="$(echo "$commit_body" | grep -oP 'Tag: \Kv[0-9]+\.[0-9]+\.[0-9]+')"
          release_name="$(echo "$commit_body" | grep -oP 'Release Name: \K.*')"

          echo "::set-output name=tag_name::$tag_name"
          echo "::set-output name=release_name::$release_name"

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with: 
          workflow: flutter-master-build.yaml
          workflow_search: false
          workflow_conclusion: success

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_message.outputs.tag_name }}
          release_name: ${{ steps.get_message.outputs.release_name }}
          body: "Automated release based on commit message."
          draft: false
          prerelease: false
    
      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './app-release-apk'
          asset_name: artifact.zip
          asset_content_type: application/zip
